# Generated by Django 5.0.6 on 2024-10-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='poster',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
